=== hougesen/mdsf/tools/tool.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tool",
  "type": "object",
  "required": [
    "binary",
    "categories",
    "commands",
    "description",
    "homepage",
    "languages",
    "tests"
  ],
  "properties": {
    "binary": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "commands": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "description": {
      "type": "string"
    },
    "homepage": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "name": {
      "type": ["string", "null"]
    },
    "npm": {
      "type": ["string", "null"]
    },
    "php": {
      "type": ["string", "null"]
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ToolTest"
      }
    }
  },
  "definitions": {
    "ToolTest": {
      "type": "object",
      "required": ["command", "language", "test_input", "test_output"],
      "properties": {
        "command": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "test_input": {
          "type": "string"
        },
        "test_output": {
          "type": "string"
        }
      }
    }
  }
}

=== hougesen/mdsf/tools/meson/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "meson",
  "categories": ["formatter"],
  "commands": {
    "fmt": ["fmt", "-i", "$PATH"]
  },
  "description": "Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible",
  "homepage": "https://mesonbuild.com/",
  "languages": ["meson"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/gci/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "gci",
  "categories": ["formatter"],
  "commands": {
    "": ["write", "--skip-generated", "--skip-vender", "$PATH"]
  },
  "description": "GCI, a tool that control golang package import order and make it always deterministic",
  "homepage": "https://github.com/daixiang0/gci",
  "languages": ["go"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/hindent/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "hindent",
  "categories": ["formatter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "",
  "homepage": "",
  "languages": ["haskell"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "haskell",
      "test_input": "\naddNumbers::Int->Int->Int\naddNumbers a b = do\n        a + b\n        ",
      "test_output": "addNumbers :: Int -> Int -> Int\naddNumbers a b = do\n  a + b\n"
    }
  ]
}

=== hougesen/mdsf/tools/bibtex-tidy/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "bibtex-tidy",
  "categories": ["formatter"],
  "commands": {
    "": ["-m", "$PATH"]
  },
  "description": "Cleaner and Formatter for BibTeX files",
  "homepage": "https://github.com/FlamingTempura/bibtex-tidy",
  "languages": ["bibtex"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/dockfmt/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "dockfmt",
  "categories": ["formatter"],
  "commands": {
    "": ["fmt", "-w", "$PATH"]
  },
  "description": "Dockerfile format and parser. Like `gofmt` but for Dockerfiles",
  "homepage": "https://github.com/jessfraz/dockfmt",
  "languages": ["docker"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/pyment/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "pyment",
  "categories": ["formatter"],
  "commands": {
    "": ["-w", "$PATH"]
  },
  "description": "Format and convert Python docstrings and generates patches",
  "homepage": "https://github.com/dadadel/pyment",
  "languages": ["python"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/golines/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "golines",
  "categories": ["formatter"],
  "commands": {
    "": ["-w", "$PATH"]
  },
  "description": "A golang formatter that fixes long lines",
  "homepage": "https://github.com/segmentio/golines",
  "languages": ["go"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "go",
      "test_input": "package main\n\nimport (\n\t\"os\"\n\t\"fmt\"\n)\n\nfunc add(a int, b int) int {\n\tfmt.Print(a)\n\tfmt.Print(b)\n\treturn a + b\n}\n",
      "test_output": "package main\n\nimport (\n\t\"fmt\"\n)\n\nfunc add(a int, b int) int {\n\tfmt.Print(a)\n\tfmt.Print(b)\n\treturn a + b\n}\n"
    }
  ]
}

=== hougesen/mdsf/tools/jsonnetfmt/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "jsonnetfmt",
  "categories": ["formatter"],
  "commands": {
    "": ["-i", "$PATH"]
  },
  "description": "Formatter for automatically fixing jsonnet stylistic problems",
  "homepage": "https://jsonnet.org/learning/tools.html",
  "languages": ["jsonnet"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}
