=== hougesen/mdsf/tools/tool.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tool",
  "type": "object",
  "required": [
    "binary",
    "categories",
    "commands",
    "description",
    "homepage",
    "languages",
    "tests"
  ],
  "properties": {
    "binary": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "commands": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "description": {
      "type": "string"
    },
    "homepage": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "name": {
      "type": ["string", "null"]
    },
    "npm": {
      "type": ["string", "null"]
    },
    "php": {
      "type": ["string", "null"]
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ToolTest"
      }
    }
  },
  "definitions": {
    "ToolTest": {
      "type": "object",
      "required": ["command", "language", "test_input", "test_output"],
      "properties": {
        "command": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "test_input": {
          "type": "string"
        },
        "test_output": {
          "type": "string"
        }
      }
    }
  }
}

=== hougesen/mdsf/tools/dhall/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "dhall",
  "categories": ["formatter"],
  "commands": {
    "": ["format", "$PATH"]
  },
  "description": "Format Dhall files",
  "homepage": "https://dhall-lang.org/",
  "languages": ["dhall"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/brighterscript-formatter/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "bsfmt",
  "categories": ["formatter"],
  "commands": {
    "": ["$PATH", "--write"]
  },
  "description": "A code formatter for BrightScript and BrighterScript",
  "homepage": "https://github.com/rokucommunity/brighterscript-formatter",
  "languages": ["brightscript", "brighterscript"],
  "name": null,
  "npm": "brighterscript-formatter",
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/fantomas/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "fantomas",
  "categories": ["formatter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "FSharp source code formatter",
  "homepage": "https://github.com/fsprojects/fantomas",
  "languages": ["fsharp"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "fsharp",
      "test_input": "\nlet add a b  =  a +  b\n            ",
      "test_output": "let add a b = a + b\n"
    }
  ]
}

=== hougesen/mdsf/tools/pyink/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "pyink",
  "categories": ["formatter"],
  "commands": {
    "": ["--quiet", "$PATH"]
  },
  "description": "Pyink is a Python formatter, forked from Black with a few different formatting behaviors",
  "homepage": "https://github.com/google/pyink",
  "languages": ["python"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "python",
      "test_input": "def add( a: int ,  b:int)->int: return a+b",
      "test_output": "def add(a: int, b: int) -> int:\n    return a + b\n"
    }
  ]
}

=== hougesen/mdsf/tools/cabal-fmt/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "cabal-fmt",
  "categories": ["formatter"],
  "commands": {
    "": ["--inplace", "$PATH"]
  },
  "description": "An experiment of formatting .cabal files",
  "homepage": "https://github.com/phadej/cabal-fmt",
  "languages": ["cabal"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/ansible-lint/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "ansible-lint",
  "categories": ["linter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "ansible-lint checks playbooks for practices and behavior that could potentially be improved and can fix some of the most common ones for you",
  "homepage": "https://github.com/ansible/ansible-lint",
  "languages": ["ansible"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/mypy/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "mypy",
  "categories": ["linter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "Optional static typing for Python",
  "homepage": "https://github.com/python/mypy",
  "languages": ["python"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/yapf/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "yapf",
  "categories": ["formatter"],
  "commands": {
    "": ["--in-place", "$PATH"]
  },
  "description": "A formatter for Python files",
  "homepage": "https://github.com/google/yapf",
  "languages": ["python"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "python",
      "test_input": "def add( a: int ,  b:int)->int: return a+b",
      "test_output": "def add(a: int, b: int) -> int:\n    return a + b\n"
    }
  ]
}
