=== hougesen/mdsf/tools/tool.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tool",
  "type": "object",
  "required": [
    "binary",
    "categories",
    "commands",
    "description",
    "homepage",
    "languages",
    "tests"
  ],
  "properties": {
    "binary": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "commands": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "description": {
      "type": "string"
    },
    "homepage": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "name": {
      "type": ["string", "null"]
    },
    "npm": {
      "type": ["string", "null"]
    },
    "php": {
      "type": ["string", "null"]
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ToolTest"
      }
    }
  },
  "definitions": {
    "ToolTest": {
      "type": "object",
      "required": ["command", "language", "test_input", "test_output"],
      "properties": {
        "command": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "test_input": {
          "type": "string"
        },
        "test_output": {
          "type": "string"
        }
      }
    }
  }
}

=== hougesen/mdsf/tools/terragrunt/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "terragrunt",
  "categories": ["formatter"],
  "commands": {
    "hclfmt": ["hclfmt", "--terragrunt-hclfmt-file", "$PATH"]
  },
  "description": "Recursively find hcl files and rewrite them into a canonical format",
  "homepage": "https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt",
  "languages": ["hcl"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/ocamlformat/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "ocamlformat",
  "categories": ["formatter"],
  "commands": {
    "": [
      "--ignore-invalid-option",
      "--inplace",
      "--enable-outside-detected-project",
      "$PATH"
    ]
  },
  "description": "Auto-formatter for OCaml code",
  "homepage": "https://github.com/ocaml-ppx/ocamlformat",
  "languages": ["ocaml"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "ocaml",
      "test_input": "\nlet add a b  =  a +  b\n            ",
      "test_output": "let add a b = a + b\n"
    }
  ]
}

=== hougesen/mdsf/tools/buf/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "buf",
  "categories": ["formatter"],
  "commands": {
    "format": ["format", "--write", "$PATH"]
  },
  "description": "The best way of working with Protocol Buffers",
  "homepage": "https://buf.build/docs/reference/cli/buf/format/",
  "languages": ["protobuf"],
  "name": null,
  "npm": "@bufbuild/buf",
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "protobuf",
      "test_input": "service SearchService {\n                              rpc Search (SearchRequest) returns (SearchResponse);\n                               }",
      "test_output": "service SearchService {\n  rpc Search(SearchRequest) returns (SearchResponse);\n}\n"
    }
  ]
}

=== hougesen/mdsf/tools/crlfmt/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "crlfmt",
  "categories": ["formatter"],
  "commands": {
    "": ["-w", "$PATH"]
  },
  "description": "Formatter for CockroachDB's additions to the Go style guide",
  "homepage": "https://github.com/cockroachdb/crlfmt",
  "languages": ["go"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/xmlformat/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "xmlformat",
  "categories": ["formatter"],
  "commands": {
    "": ["--overwrite", "$PATH"]
  },
  "description": "Format and compress XML documents",
  "homepage": "https://github.com/pamoller/xmlformatter",
  "languages": ["xml"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": [
    {
      "command": "",
      "language": "xml",
      "test_input": "\n<note>\n  <to>Tove</to>\n          <from>Jani</from>\n      <heading>Reminder</heading>\n        <body>Don't forget me this weekend!</body>\n   </note>",
      "test_output": "<note>\n  <to>Tove</to>\n  <from>Jani</from>\n  <heading>Reminder</heading>\n  <body>Don't forget me this weekend!</body>\n</note>"
    }
  ]
}

=== hougesen/mdsf/tools/djade/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "djade",
  "categories": ["formatter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "A Django template formatter",
  "homepage": "https://github.com/adamchainz/djade",
  "languages": ["python", "django"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/salt-lint/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "salt-lint",
  "categories": ["linter"],
  "commands": {
    "": ["$PATH"]
  },
  "description": "A command-line utility that checks for best practices in SaltStack",
  "homepage": "https://github.com/warpnet/salt-lint",
  "languages": ["salt"],
  "name": null,
  "npm": null,
  "php": null,
  "tests": []
}

=== hougesen/mdsf/tools/dprint/plugin.json
{
  "$schema": "../tool.schema.json",
  "binary": "dprint",
  "categories": ["formatter"],
  "commands": {
    "fmt": ["fmt", "$PATH"]
  },
  "description": "A pluggable and configurable code formatting platform written in Rust",
  "homepage": "https://dprint.dev/",
  "languages": [],
  "name": null,
  "npm": "dprint",
  "php": null,
  "tests": []
}
